import { Product } from "./components/type";

export const userProducts: Product[] = [
  {
    id: "cc-001",
    name: "Tín chỉ Carbon - Dự án Lâm Lắc",
    type: "carbon_credits",
    description:
      "Dự án trồng rừng và bảo tồn đa dạng sinh học tại Lâm Đồng, góp phần giảm phát thải CO2 và bảo vệ môi trường. Dự án được chứng nhận theo tiêu chuẩn VCS (Verified Carbon Standard) và CCB (Climate, Community & Biodiversity Standards).",
    purchaseDate: "2025-01-05",
    status: "active",
    expiryDate: "2030-01-05",
    image: "/images/after-reforestation.png",
    features: [
      "Chứng nhận VCS",
      "Bảo tồn đa dạng sinh học",
      "Hỗ trợ cộng đồng địa phương",
      "Trồng xen canh 3-5 loài cây",
    ],
    price: 250000000,
    projectLocation: "Lâm Đồng, Việt Nam",
    carbonAmount: 5000,
    carbonUsed: 1250,
    verificationStandard: "VCS (Verified Carbon Standard)",
  },
  {
    id: "cc-002",
    name: "Tín chỉ Carbon - Dự án Rừng Cát Tiên",
    type: "carbon_credits",
    description:
      "Dự án trồng rừng và bảo tồn đa dạng sinh học tại Vườn Quốc gia Cát Tiên, góp phần giảm phát thải CO2 và bảo vệ môi trường. Dự án được chứng nhận theo tiêu chuẩn VCS (Verified Carbon Standard) và CCB (Climate, Community & Biodiversity Standards).",
    purchaseDate: "2024-11-15",
    status: "active",
    expiryDate: "2029-11-15",
    image: "/images/before-reforestation.png",
    features: [
      "Chứng nhận CCB",
      "Bảo vệ động vật hoang dã",
      "Phát triển bền vững",
      "Diện tích dự án từ 20ha trở lên",
    ],
    price: 300000000,
    projectLocation: "Đồng Nai, Việt Nam",
    carbonAmount: 6000,
    carbonUsed: 2000,
    verificationStandard: "CCB (Climate, Community & Biodiversity Standards)",
  },
  {
    id: "ca-001",
    name: "Carbon Toàn Thư 4.0 - Gói Chuyên Gia",
    type: "carbon_accounting",
    description:
      "Kho tri thức toàn diện với hơn 600 tài liệu, nghiên cứu, báo cáo chuyên sâu về Carbon Credits, ESG & CSR, kết hợp với trợ lý AI CarbonSeek hiện đại nhất hiện nay. Bao gồm công cụ phân tích, báo cáo tự động và tư vấn chuyên sâu.",
    purchaseDate: "2025-03-15",
    status: "active",
    expiryDate: "2026-03-15",
    image:
      "https://res.cloudinary.com/dyticflm3/image/upload/v1744629737/Robot_working_rsz_q5yv9k.jpg",
    features: [
      "Trợ lý AI CarbonSeek",
      "Hơn 600 tài liệu chuyên sâu",
      "Tư vấn 1-1 với chuyên gia",
      "Báo cáo thị trường hàng quý",
      "Hội thảo trực tuyến hàng quý",
    ],
    price: 560000,
    usageStats: {
      totalUsage: 120,
      lastMonthUsage: 35,
      trend: "up",
    },
    subscriptionTier: "professional",
    nextPayment: "2026-03-15",
  },
  {
    id: "ca-002",
    name: "Carbon Toàn Thư 4.0 - Gói Doanh Nghiệp",
    type: "carbon_accounting",
    description:
      "Giải pháp toàn diện giúp doanh nghiệp tiếp cận tri thức về tín chỉ carbon, ESG & CSR thông qua nền tảng AI CarbonSeek nâng cao. Bao gồm quản lý người dùng theo phòng ban, đào tạo nội bộ tùy chỉnh và tư vấn chiến lược carbon & CBAM.",
    purchaseDate: "2024-12-10",
    status: "active",
    expiryDate: "2025-12-10",
    image:
      "https://res.cloudinary.com/dyticflm3/image/upload/v1744629737/Robot_working_rsz_q5yv9k.jpg",
    features: [
      "Tất cả tính năng gói Chuyên gia",
      "Quản lý người dùng theo phòng ban",
      "Đào tạo nội bộ tùy chỉnh",
      "Tư vấn chiến lược carbon & CBAM",
      "Tích hợp API CarbonSeek",
      "Báo cáo chuyên ngành riêng",
    ],
    price: 0, // Custom pricing
    usageStats: {
      totalUsage: 250,
      lastMonthUsage: 60,
      trend: "up",
    },
    subscriptionTier: "enterprise",
    nextPayment: "2025-12-10",
  },
  {
    id: "ca-003",
    name: "Carbon Toàn Thư 4.0 - Gói Dùng Thử",
    type: "carbon_accounting",
    description:
      "Trải nghiệm miễn phí các tính năng cơ bản của Carbon Toàn Thư 4.0 trong 14 ngày. Bao gồm truy cập hạn chế vào kho tài liệu, sử dụng AI CarbonSeek với giới hạn truy vấn, và xem các báo cáo mẫu.",
    purchaseDate: "2025-04-01",
    status: "active",
    expiryDate: "2025-04-15",
    image:
      "https://res.cloudinary.com/dyticflm3/image/upload/v1744629737/Robot_working_rsz_q5yv9k.jpg",
    features: [
      "Trợ lý AI CarbonSeek (giới hạn)",
      "Truy cập 50 tài liệu cơ bản",
      "Báo cáo mẫu",
      "Hỗ trợ qua email",
    ],
    price: 0, // Free trial
    usageStats: {
      totalUsage: 15,
      lastMonthUsage: 15,
      trend: "up",
    },
    subscriptionTier: "basic",
    nextPayment: "2025-04-15",
  },
  {
    id: "ic-001",
    name: "Chứng chỉ Quốc tế - Gói Nghiên cứu",
    type: "international_certificates",
    description:
      "Chứng chỉ nghiên cứu về carbon và biến đổi khí hậu, được cấp bởi Columbia Southern University (CSU) và Tín Chỉ Carbon Việt Nam. Trang bị kiến thức nền tảng và phương pháp nghiên cứu trong lĩnh vực carbon.",
    purchaseDate: "2025-02-10",
    status: "active",
    expiryDate: "2027-02-10",
    image: "/images/certificate-sample.png",
    features: [
      "Phương pháp nghiên cứu",
      "Đào tạo 3 tháng",
      "Hỗ trợ học thuật",
      "Tiếp cận cơ sở dữ liệu quốc tế",
    ],
    price: 5500000,
    certificationLevel: "Nghiên cứu",
    courseProgress: 85,
    lastAccessed: "2025-03-01",
    issuer: "Columbia Southern University (CSU)",
  },
  {
    id: "ic-002",
    name: "Chứng chỉ Quốc tế - Gói Chuyên gia",
    type: "international_certificates",
    description:
      "Chứng chỉ chuyên gia toàn diện về quản lý carbon, kiểm toán carbon và tư vấn ESG, được cấp bởi Columbia Southern University (CSU) và Tín Chỉ Carbon Việt Nam. Đào tạo chuyên gia có khả năng tư vấn và triển khai các dự án carbon chuyên nghiệp.",
    purchaseDate: "2024-10-20",
    status: "active",
    expiryDate: "2026-10-20",
    image: "/images/certificate-sample.png",
    features: [
      "Quản lý carbon chuyên nghiệp",
      "Kiểm toán carbon",
      "Tư vấn ESG",
      "Đào tạo 6 tháng",
      "Thực hành với doanh nghiệp thật",
      "Tư vấn nghề nghiệp",
    ],
    price: 12500000,
    certificationLevel: "Chuyên gia",
    courseProgress: 100,
    lastAccessed: "2025-02-15",
    issuer: "Columbia Southern University (CSU)",
  },
];
