export const aboutLanguage = {
  vi: {
    about_page_title: "Về Chúng Tôi",
    about_page_subtitle: "Khám phá câu chuyện và sứ mệnh của chúng tôi trong việc bảo vệ môi trường và phát triển bền vững.",
    about_us_section: "Về Chúng Tôi",
    about_us_content: "Chúng tôi là một tổ chức tiên phong trong lĩnh vực phát triển bền vững và bảo vệ môi trường. Với nhiều năm kinh nghiệm, chúng tôi cam kết mang đến những giải pháp hiệu quả để giảm thiểu tác động của biến đổi khí hậu.",
    about_us_content_2: "Đội ngũ của chúng tôi bao gồm các chuyên gia hàng đầu trong lĩnh vực môi trường, nông nghiệp bền vững và công nghệ xanh. Chúng tôi tin rằng mỗi hành động nhỏ đều có thể tạo ra sự thay đổi lớn cho tương lai của hành tinh.",
    vision_mission: "Tầm Nhìn & Sứ Mệnh",
    vision: "Tầm Nhìn:",
    vision_content: "Trở thành đối tác tin cậy hàng đầu trong việc thúc đẩy phát triển bền vững và bảo vệ môi trường tại Việt Nam và khu vực Đông Nam Á.",
    mission: "Sứ Mệnh:",
    mission_content: "Cung cấp các giải pháp toàn diện về tín chỉ carbon, nông nghiệp bền vững và giáo dục môi trường để xây dựng một tương lai xanh hơn cho thế hệ mai sau.",
    core_values: "Giá Trị Cốt Lõi",
    core_value_1: "Bền Vững",
    core_value_1_desc: "Cam kết thực hiện các hoạt động có trách nhiệm với môi trường và xã hội.",
    core_value_2: "Sáng Tạo",
    core_value_2_desc: "Liên tục đổi mới và phát triển các giải pháp công nghệ tiên tiến.",
    core_value_3: "Minh Bạch",
    core_value_3_desc: "Đảm bảo tính minh bạch trong mọi hoạt động và báo cáo.",
    core_value_4_desc: "Thúc đẩy hợp tác với các đối tác để tạo ra tác động tích cực lớn hơn.",
    contact_now: "Liên Hệ Ngay",
  },
  en: {
    about_page_title: "About Us",
    about_page_subtitle: "Discover our story and mission in environmental protection and sustainable development.",
    about_us_section: "About Us",
    about_us_content: "We are a pioneering organization in sustainable development and environmental protection. With years of experience, we are committed to providing effective solutions to mitigate the impacts of climate change.",
    about_us_content_2: "Our team consists of leading experts in environmental science, sustainable agriculture, and green technology. We believe that every small action can create significant change for the future of our planet.",
    vision_mission: "Vision & Mission",
    vision: "Vision:",
    vision_content: "To become the leading trusted partner in promoting sustainable development and environmental protection in Vietnam and Southeast Asia.",
    mission: "Mission:",
    mission_content: "To provide comprehensive solutions for carbon credits, sustainable agriculture, and environmental education to build a greener future for future generations.",
    core_values: "Core Values",
    core_value_1: "Sustainability",
    core_value_1_desc: "Commitment to conducting environmentally and socially responsible activities.",
    core_value_2: "Innovation",
    core_value_2_desc: "Continuously innovating and developing advanced technological solutions.",
    core_value_3: "Transparency",
    core_value_3_desc: "Ensuring transparency in all activities and reporting.",
    core_value_4_desc: "Promoting collaboration with partners to create greater positive impact.",
    contact_now: "Contact Now",
  },
};
