// Mock data for projects
const mockProjects = [
  {
    id: 1,
    name: "Dự án trồng rừng Tây Nguyên",
    description: "Dự án trồng và phục hồi rừng tại khu vực Tây Nguyên",
    status: "active",
    registrationDate: "2023-10-15",
    carbonCredits: 25.5,
    type: "forestry",
    location: "Tây Nguyên",
  },
  {
    id: 2,
    name: "Năng lượng mặt trời Ninh Thuận",
    description: "Dự án lắp đặt các tấm pin năng lượng mặt trời tại Ninh Thuận",
    status: "pending",
    registrationDate: "2023-11-20",
    carbonCredits: 18.2,
    type: "renewable",
    location: "Ninh Thuận",
  },
  {
    id: 3,
    name: "Bảo tồn đất ngập nước Đồng Tháp",
    description: "Dự án bảo tồn và phục hồi hệ sinh thái đất ngập nước",
    status: "completed",
    registrationDate: "2023-08-05",
    carbonCredits: 42.8,
    type: "conservation",
    location: "Đồng Tháp",
  },
  {
    id: 4,
    name: "Chuyển đổi chất thải hữu cơ Hà Nội",
    description: "Dự án xử lý và tái chế chất thải hữu cơ thành phân bón",
    status: "active",
    registrationDate: "2023-09-12",
    carbonCredits: 15.3,
    type: "waste",
    location: "Hà Nội",
  },
];
